### ISSUE TITLE
Hide Slides

### ISSUE THREAD

**Issue by MaximilianKoenig** [hpi-swa-teaching/PowerSqueak#10]
As a presentation creator I want to be able to hide slides for presenting in order to keep important slides which should not be seen in presentation mode.

Acceptance criteria:
- [x] right click the miniature slide and be able to choose the button "hide slide"
- [x] once the button is selected mark the miniature slide in a specific way
- [x] the slide will be skipped in presentation mode
- [x] be able to "unhide" the slide

Estimated effort: 5

**Comment by MrModder** [comment]
Fix Bug regarding unhiding and hiding again
Insert a clearer image
