### ISSUE TITLE
UI refactoring - menu bar

### ISSUE THREAD

**Issue by MrModder** [hpi-swa-teaching/PowerSqueak#102]
In light of recent development, it has become obvious, that the current menu bar design does not really make sense anymore.

Please rework the menu bar to be similar to the mockup that was created during the customer meeting.

Estimated effort: 8

**Comment by MrModder** [comment]
@monasobh Please upload the mockup we created during the customer meeting

**Comment by markbader** [comment]
![sketch ui refactoring](https://user-images.githubusercontent.com/29625900/58511179-95390700-819a-11e9-8428-f4fa55b59da6.jpg)

**Comment by MrModder** [comment]
New estimated effort: 5
