### ISSUE TITLE
Textboxes Resize When Text Exceeds Width

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa-teaching/PowerSqueak#29]
As a presentation creator when editing text boxes, I want them to increase their width when my written text exceeds the width, in order to not have to resize them manually.

Acceptance criteria:
- [ ] Text box extends width
- [ ] Text box stops extending, when slide border is reached

Estimated effort: 11

**Comment by LeonBein** [comment]
Question: Is this still a relevant user story?

**Comment by MrModder** [comment]
This does not seem to be a useful feature
