### ISSUE TITLE
Basic shapes and arrows

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/PowerSqueak#49]
### Original issue (by @ekrebs5 )
I want to be able to add basic shapes (lines, rectangle, triangles, circles/ellipses) and arrows to my presentation, in order to easily visualize stuff without making my own pictures each time.

This also requires for me to able to determine the order of things, eg that my text is above my rectangle.

Shapes should have a filling color and an outline color, arrows one color.

### User story
As a presentation creator I want to be able to add basic shapes (lines, rectangle, triangles, circles/ellipses and arrows) to my presentation, in order to easily visualize stuff without adding a lot of pictures.

Acceptance criteria:
- [x] A button exists to add shapes
- [x] The button lets you choose a shape to add
- [x] The selected shape can be added to a slide
- [x] The shape can be rescaled using the handles
- [x] The shape scales correctly on the slide

Estimated effort: 3

**Comment by MrModder** [comment]
@ekrebs5 You can already set the order of slide elements by right-clicking them and selecting "bring to front" or "send to back" respectively
Be aware though, that slide element order is currently not saved to the file system.
This is a bug we found recently and did not have the time to fix yet
