### ISSUE TITLE
Move Slides Per Miniature Dragndrop

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa-teaching/PowerSqueak#69]
As a presentation creator I want to be able to drag a slide miniature in the miniature view and drop it at another location in the view in order to move the slide with this action.

Acceptance criteria:
- [ ] Slide miniatures can be dragged inside the miniature view
- [ ] When stopping to drag, the slide the miniature belongs to is moved to the index the miniature is located when dropping

Estimated effort: 13

**Comment by MrModder** [comment]
This user story is most likely going to be dropped in favor of #99 and #100

**Comment by MrModder** [comment]
As #99 and #100 are now implemented, this feature already exists
